### ISSUE TITLE
fmgilham fork of bible-mode seems to work better than the original one

### ISSUE THREAD

**Issue by OrionRandD** [Zacalot/bible-mode#9]
Is it possible to talk with this person?
https://github.com/fmgilham
His fork of bible-mode is working beautifully.
But, yours, the original, is buggy, at least here.
When I use yours, it hangs Emacs as if it triggers an infinite loop.
But, when I use that fork, everything works ok.
Could you have a look in his TODO file?

**Comment by Zacalot** [comment]
Yeah I wouldn't consider myself an elisp expert, especially not when I first cobbled this together, so sorry you're having trouble. Great that fork works for you, is there a reason you can't just continue to use it? There's so many changes to the program made in that fork that I wouldn't have a clue what change fixed your issue. Otherwise, feel free to describe how this bible-mode is failing you though, such as if it crashes when you perform a specific action or something along those lines and I could try looking into it.

There are definitely a lot of improvements in that fork there but it very much looks to be a work-in-progress so I'd hesitate in using it right now, especially since some passages like Psalm 119 don't properly in it currently, as noted in a comment by that author. Perhaps we could look into merging changes later down the road, but for now I think it's fine to keep things separate, especially since I'm not familiar with open source project collaboration. 

Thanks for bringing this up though, I've updated the repo to point to that fork as a solution to the problem, and I've added a GPL3 license since I realized it was missing.

**Comment by OrionRandD** [comment]
Yeah I've just pointed that to you, exactly hoping that, perhaps, would be a good idea to work together with fmgilham, since the effort you are doing is not redundant. I already have told him about, perhaps, suggesting the code to be part of MELPA/ELPA and have showed him the way he could ask for advice on this matter.
You can see the discussion here:
https://github.com/fmgilham/lisp-logo/issues
and give your suggestions...
God bless,
and thx for to program.

**Comment by ghost** [comment]
Sorry for so many changes to the code! I used to program in Lisp for a living and I changed it to be more in Lisp idiomatic style for my own sake of understanding it. I also didn't document my changes; I just tried to document the code itself so I could remember what it did. I didn't really expect anyone else to even see it!

I'm planning on "cherry picking" your recent updates. And if you are OK with it, I'll try to make an Emacs package of this thing.

I'm also grateful for this code and use it a lot! So thank you for writing it in the first place.

**Comment by Zacalot** [comment]
@fmgilham Hey! Awesome that you're acquainted with Lisp - do absolutely whatever you want with the project and my repository here, I'd be thrilled if you publish it as an official package as well. That's why I made sure to put the GPLv3 license in it the other day, though that may go without saying for Emacs packages, lol. I personally don't have any plans to take the project in such a direction myself since people report issues with it relatively regularly and I don't feel experienced with ELisp or Emacs development enough to do it justice. I would only prefer that if you make an official release you first ensure all the "difficult" chapters work, such as Psalm 119 as mentioned in your codebase.

Glad you've found the package useful, thanks for working to improve it and apologies for the messy code! Also feel free to contact me in an issue here or through any other way Github may provide if you ever need anything.
